---
- name: Install MySQL server and its python transport
  apt:
    name={{ item }}
    state=present
  with_items:
    - mysql-server
    - python-mysqldb

- name: Release resources for local configuration
  service:
    name={{ item }}
    state=stopped
  notify: restart heartbeat
  with_items:
    - heartbeat
#    - drbd

- name: Allow root access to MySQL server through the cluster IP
  include: root_access_on_primary.yml
  when: "primary is defined"

- name: Stop and disable MySQL server
  service:
    name=mysql
    enabled=no
    state=stopped
  notify: restart heartbeat

- name: Allow MySQL to listen on all interfaces
  lineinfile:
    dest=/etc/mysql/my.cnf
    regexp='^bind-address(.*)'
    line='# bind-address\1'
    backrefs=yes
    state=present
  notify: restart heartbeat

- name: Create data directory
  file:
    path=/data
    state=directory

- name: Check data symlink
  stat:
    path=/var/lib/mysql
  register: stats

- name: Configure MySQL data on the DRBD device
  include: on_primary.yml
  when: "primary is defined"

- name: Remove the MySQL data
  file:
    path=/var/lib/mysql/
    state=absent
  when: "primary is not defined and stats.stat.isdir"

- name: Link the MySQL data from its original location
  file:
    src=/data/mysql/
    dest=/var/lib/mysql
    state=link
